name: Build and push Docker image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        repository: wuvt/postgres-backup
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true
        add_git_labels: true
    - name: Build and push Docker image to GitHub Package Registry
      uses: docker/build-push-action@v1
      with:
        repository: wuvt/postgres-backup
        username: wuvt
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tag_with_ref: true
        add_git_labels: true
